

#include <QtGlobal>

// Automatically generated by extract_strings_qt.py
#ifdef __GNUC__
#define UNUSED __attribute__((unused))
#else
#define UNUSED
#endif
static const char UNUSED *hoot_strings[] = {
QT_TRANSLATE_NOOP("hoot-core", "The %s developers"),
QT_TRANSLATE_NOOP("hoot-core", ""
"%s corrupt. Try using the wallet tool hoot-wallet to salvage or restoring a "
"backup."),
QT_TRANSLATE_NOOP("hoot-core", ""
"%s file contains all private keys from this wallet. Do not share it with "
"anyone!"),
QT_TRANSLATE_NOOP("hoot-core", ""
"%s uses exact denominated amounts to send funds, you might simply need to "
"mix some more coins."),
QT_TRANSLATE_NOOP("hoot-core", ""
"-maxtxfee is set very high! Fees this large could be paid on a single "
"transaction."),
QT_TRANSLATE_NOOP("hoot-core", ""
"Cannot obtain a lock on data directory %s. %s is probably already running."),
QT_TRANSLATE_NOOP("hoot-core", ""
"Cannot provide specific connections and have addrman find outgoing "
"connections at the same."),
QT_TRANSLATE_NOOP("hoot-core", ""
"Distributed under the MIT software license, see the accompanying file %s or "
"%s"),
QT_TRANSLATE_NOOP("hoot-core", ""
"Error loading %s: You can't enable HD on an already existing non-HD wallet"),
QT_TRANSLATE_NOOP("hoot-core", ""
"Error reading %s! All keys read correctly, but transaction data or address "
"book entries might be missing or incorrect."),
QT_TRANSLATE_NOOP("hoot-core", ""
"Error: Listening for incoming connections failed (listen returned error %s)"),
QT_TRANSLATE_NOOP("hoot-core", ""
"Failed to create backup, file already exists! This could happen if you "
"restarted wallet in less than 60 seconds. You can continue if you are ok "
"with this."),
QT_TRANSLATE_NOOP("hoot-core", ""
"Fee estimation failed. Fallbackfee is disabled. Wait a few blocks or enable -"
"fallbackfee."),
QT_TRANSLATE_NOOP("hoot-core", ""
"Found unconfirmed denominated outputs, will wait till they confirm to "
"continue."),
QT_TRANSLATE_NOOP("hoot-core", ""
"Incorrect or no devnet genesis block found. Wrong datadir for devnet "
"specified?"),
QT_TRANSLATE_NOOP("hoot-core", ""
"Invalid -socketevents ('%s') specified. Only these modes are supported: %s"),
QT_TRANSLATE_NOOP("hoot-core", ""
"Invalid amount for -maxtxfee=<amount>: '%s' (must be at least the minrelay "
"fee of %s to prevent stuck transactions)"),
QT_TRANSLATE_NOOP("hoot-core", ""
"Make sure to encrypt your wallet and delete all non-encrypted backups after "
"you have verified that the wallet works!"),
QT_TRANSLATE_NOOP("hoot-core", ""
"More than one onion bind address is provided. Using %s for the automatically "
"created Tor onion service."),
QT_TRANSLATE_NOOP("hoot-core", ""
"Please check that your computer's date and time are correct! If your clock "
"is wrong, %s will not work properly."),
QT_TRANSLATE_NOOP("hoot-core", ""
"Please contribute if you find %s useful. Visit %s for further information "
"about the software."),
QT_TRANSLATE_NOOP("hoot-core", ""
"Prune configured below the minimum of %d MiB.  Please use a higher number."),
QT_TRANSLATE_NOOP("hoot-core", ""
"Prune: last wallet synchronisation goes beyond pruned data. You need to -"
"reindex (download the whole blockchain again in case of pruned node)"),
QT_TRANSLATE_NOOP("hoot-core", ""
"SQLiteDatabase: Unknown sqlite wallet schema version %d. Only version %d is "
"supported"),
QT_TRANSLATE_NOOP("hoot-core", ""
"The block database contains a block which appears to be from the future. "
"This may be due to your computer's date and time being set incorrectly. Only "
"rebuild the block database if you are sure that your computer's date and "
"time are correct"),
QT_TRANSLATE_NOOP("hoot-core", ""
"The transaction amount is too small to send after the fee has been deducted"),
QT_TRANSLATE_NOOP("hoot-core", ""
"This error could occur if this wallet was not shutdown cleanly and was last "
"loaded using a build with a newer version of Berkeley DB. If so, please use "
"the software that last loaded this wallet"),
QT_TRANSLATE_NOOP("hoot-core", ""
"This is a pre-release test build - use at your own risk - do not use for "
"mining or merchant applications"),
QT_TRANSLATE_NOOP("hoot-core", ""
"This is the transaction fee you may discard if change is smaller than dust "
"at this level"),
QT_TRANSLATE_NOOP("hoot-core", ""
"This is the transaction fee you may pay when fee estimates are not available."),
QT_TRANSLATE_NOOP("hoot-core", ""
"Total length of network version string (%i) exceeds maximum length (%i). "
"Reduce the number or size of uacomments."),
QT_TRANSLATE_NOOP("hoot-core", ""
"Transaction index can't be disabled with governance validation enabled. "
"Either start with -disablegovernance command line switch or enable "
"transaction index."),
QT_TRANSLATE_NOOP("hoot-core", ""
"Transaction needs a change address, but we can't generate it. Please call "
"keypoolrefill first."),
QT_TRANSLATE_NOOP("hoot-core", ""
"Unable to replay blocks. You will need to rebuild the database using -"
"reindex-chainstate."),
QT_TRANSLATE_NOOP("hoot-core", ""
"WARNING! Failed to replenish keypool, please unlock your wallet to do so."),
QT_TRANSLATE_NOOP("hoot-core", ""
"Wallet is locked, can't replenish keypool! Automatic backups and mixing are "
"disabled, please unlock your wallet to replenish keypool."),
QT_TRANSLATE_NOOP("hoot-core", ""
"Warning: Private keys detected in wallet {%s} with disabled private keys"),
QT_TRANSLATE_NOOP("hoot-core", ""
"Warning: We do not appear to fully agree with our peers! You may need to "
"upgrade, or other nodes may need to upgrade."),
QT_TRANSLATE_NOOP("hoot-core", ""
"You need to rebuild the database using -reindex to change -timestampindex"),
QT_TRANSLATE_NOOP("hoot-core", ""
"You need to rebuild the database using -reindex to go back to unpruned "
"mode.  This will redownload the entire blockchain"),
QT_TRANSLATE_NOOP("hoot-core", "%s can't be lower than %s"),
QT_TRANSLATE_NOOP("hoot-core", "%s failed"),
QT_TRANSLATE_NOOP("hoot-core", "%s is idle."),
QT_TRANSLATE_NOOP("hoot-core", "%s is not a valid backup folder!"),
QT_TRANSLATE_NOOP("hoot-core", "%s is set very high!"),
QT_TRANSLATE_NOOP("hoot-core", "%s request incomplete:"),
QT_TRANSLATE_NOOP("hoot-core", "-devnet can only be specified once"),
QT_TRANSLATE_NOOP("hoot-core", "-maxmempool must be at least %d MB"),
QT_TRANSLATE_NOOP("hoot-core", "-port must be specified when -devnet and -listen are specified"),
QT_TRANSLATE_NOOP("hoot-core", "-rpcport must be specified when -devnet and -server are specified"),
QT_TRANSLATE_NOOP("hoot-core", "A fatal internal error occurred, see debug.log for details"),
QT_TRANSLATE_NOOP("hoot-core", "Already have that input."),
QT_TRANSLATE_NOOP("hoot-core", "Automatic backups disabled"),
QT_TRANSLATE_NOOP("hoot-core", "Can't find random Masternode."),
QT_TRANSLATE_NOOP("hoot-core", "Can't mix while sync in progress."),
QT_TRANSLATE_NOOP("hoot-core", "Can't mix: no compatible inputs found!"),
QT_TRANSLATE_NOOP("hoot-core", "Cannot resolve -%s address: '%s'"),
QT_TRANSLATE_NOOP("hoot-core", "Cannot set -peerblockfilters without -blockfilterindex."),
QT_TRANSLATE_NOOP("hoot-core", "Cannot write to data directory '%s'; check permissions."),
QT_TRANSLATE_NOOP("hoot-core", "Change index out of range"),
QT_TRANSLATE_NOOP("hoot-core", "Collateral not valid."),
QT_TRANSLATE_NOOP("hoot-core", "Config setting for %s only applied on %s network when in [%s] section."),
QT_TRANSLATE_NOOP("hoot-core", "Copyright (C)"),
QT_TRANSLATE_NOOP("hoot-core", "Corrupted block database detected"),
QT_TRANSLATE_NOOP("hoot-core", "Could not find asmap file %s"),
QT_TRANSLATE_NOOP("hoot-core", "Could not parse asmap file %s"),
QT_TRANSLATE_NOOP("hoot-core", "Disk space is too low!"),
QT_TRANSLATE_NOOP("hoot-core", "Do you want to rebuild the block database now?"),
QT_TRANSLATE_NOOP("hoot-core", "Done loading"),
QT_TRANSLATE_NOOP("hoot-core", "ERROR! Failed to create automatic backup"),
QT_TRANSLATE_NOOP("hoot-core", "Entries are full."),
QT_TRANSLATE_NOOP("hoot-core", "Entry exceeds maximum size."),
QT_TRANSLATE_NOOP("hoot-core", "Error initializing block database"),
QT_TRANSLATE_NOOP("hoot-core", "Error initializing wallet database environment %s!"),
QT_TRANSLATE_NOOP("hoot-core", "Error loading %s"),
QT_TRANSLATE_NOOP("hoot-core", "Error loading %s: Private keys can only be disabled during creation"),
QT_TRANSLATE_NOOP("hoot-core", "Error loading %s: Wallet corrupted"),
QT_TRANSLATE_NOOP("hoot-core", "Error loading %s: Wallet requires newer version of %s"),
QT_TRANSLATE_NOOP("hoot-core", "Error loading %s: You can't disable HD on an already existing HD wallet"),
QT_TRANSLATE_NOOP("hoot-core", "Error loading block database"),
QT_TRANSLATE_NOOP("hoot-core", "Error opening block database"),
QT_TRANSLATE_NOOP("hoot-core", "Error reading from database, shutting down."),
QT_TRANSLATE_NOOP("hoot-core", "Error upgrading chainstate database"),
QT_TRANSLATE_NOOP("hoot-core", "Error upgrading evo database"),
QT_TRANSLATE_NOOP("hoot-core", "Error: Disk space is low for %s"),
QT_TRANSLATE_NOOP("hoot-core", "Error: Keypool ran out, please call keypoolrefill first"),
QT_TRANSLATE_NOOP("hoot-core", "Error: failed to add socket to epollfd (epoll_ctl returned error %s)"),
QT_TRANSLATE_NOOP("hoot-core", "Error: failed to add socket to kqueuefd (kevent returned error %s)"),
QT_TRANSLATE_NOOP("hoot-core", "Exceeded max tries."),
QT_TRANSLATE_NOOP("hoot-core", "Failed to clear fulfilled requests cache at %s"),
QT_TRANSLATE_NOOP("hoot-core", "Failed to clear governance cache at %s"),
QT_TRANSLATE_NOOP("hoot-core", "Failed to clear masternode cache at %s"),
QT_TRANSLATE_NOOP("hoot-core", "Failed to commit EvoDB"),
QT_TRANSLATE_NOOP("hoot-core", "Failed to create backup %s!"),
QT_TRANSLATE_NOOP("hoot-core", "Failed to create backup, error: %s"),
QT_TRANSLATE_NOOP("hoot-core", "Failed to delete backup, error: %s"),
QT_TRANSLATE_NOOP("hoot-core", "Failed to find mixing queue to join"),
QT_TRANSLATE_NOOP("hoot-core", "Failed to listen on any port. Use -listen=0 if you want this."),
QT_TRANSLATE_NOOP("hoot-core", "Failed to load fulfilled requests cache from %s"),
QT_TRANSLATE_NOOP("hoot-core", "Failed to load governance cache from %s"),
QT_TRANSLATE_NOOP("hoot-core", "Failed to load masternode cache from %s"),
QT_TRANSLATE_NOOP("hoot-core", "Failed to load sporks cache from %s"),
QT_TRANSLATE_NOOP("hoot-core", "Failed to rescan the wallet during initialization"),
QT_TRANSLATE_NOOP("hoot-core", "Failed to start a new mixing queue"),
QT_TRANSLATE_NOOP("hoot-core", "Failed to verify database"),
QT_TRANSLATE_NOOP("hoot-core", "Found enough users, signing ( waiting %s )"),
QT_TRANSLATE_NOOP("hoot-core", "Found enough users, signing ..."),
QT_TRANSLATE_NOOP("hoot-core", "Ignoring duplicate -wallet %s."),
QT_TRANSLATE_NOOP("hoot-core", "Importing..."),
QT_TRANSLATE_NOOP("hoot-core", "Incompatible mode."),
QT_TRANSLATE_NOOP("hoot-core", "Incompatible version."),
QT_TRANSLATE_NOOP("hoot-core", "Incorrect -rescan mode, falling back to default value"),
QT_TRANSLATE_NOOP("hoot-core", "Incorrect or no genesis block found. Wrong datadir for network?"),
QT_TRANSLATE_NOOP("hoot-core", "Initialization sanity check failed. %s is shutting down."),
QT_TRANSLATE_NOOP("hoot-core", "Input is not valid."),
QT_TRANSLATE_NOOP("hoot-core", "Inputs vs outputs size mismatch."),
QT_TRANSLATE_NOOP("hoot-core", "Insufficient funds."),
QT_TRANSLATE_NOOP("hoot-core", "Invalid '%s'. Allowed values: 128, 160, 192, 224, 256."),
QT_TRANSLATE_NOOP("hoot-core", "Invalid -i2psam address or hostname: '%s'"),
QT_TRANSLATE_NOOP("hoot-core", "Invalid -onion address or hostname: '%s'"),
QT_TRANSLATE_NOOP("hoot-core", "Invalid -proxy address or hostname: '%s'"),
QT_TRANSLATE_NOOP("hoot-core", "Invalid P2P permission: '%s'"),
QT_TRANSLATE_NOOP("hoot-core", "Invalid amount for -%s=<amount>: '%s'"),
QT_TRANSLATE_NOOP("hoot-core", "Invalid amount for -discardfee=<amount>: '%s'"),
QT_TRANSLATE_NOOP("hoot-core", "Invalid amount for -fallbackfee=<amount>: '%s'"),
QT_TRANSLATE_NOOP("hoot-core", "Invalid amount for -paytxfee=<amount>: '%s' (must be at least %s)"),
QT_TRANSLATE_NOOP("hoot-core", "Invalid masternodeblsprivkey. Please see documentation."),
QT_TRANSLATE_NOOP("hoot-core", "Invalid minimum number of spork signers specified with -minsporkkeys"),
QT_TRANSLATE_NOOP("hoot-core", "Invalid netmask specified in -whitelist: '%s'"),
QT_TRANSLATE_NOOP("hoot-core", "Invalid script detected."),
QT_TRANSLATE_NOOP("hoot-core", "Invalid spork address specified with -sporkaddr"),
QT_TRANSLATE_NOOP("hoot-core", "Last queue was created too recently."),
QT_TRANSLATE_NOOP("hoot-core", "Last successful action was too recent."),
QT_TRANSLATE_NOOP("hoot-core", "Loading P2P addresses..."),
QT_TRANSLATE_NOOP("hoot-core", "Loading banlist..."),
QT_TRANSLATE_NOOP("hoot-core", "Loading block index..."),
QT_TRANSLATE_NOOP("hoot-core", "Loading wallet..."),
QT_TRANSLATE_NOOP("hoot-core", "Lock is already in place."),
QT_TRANSLATE_NOOP("hoot-core", "Masternode queue is full."),
QT_TRANSLATE_NOOP("hoot-core", "Masternode:"),
QT_TRANSLATE_NOOP("hoot-core", "Missing input transaction information."),
QT_TRANSLATE_NOOP("hoot-core", "Mixing in progress..."),
QT_TRANSLATE_NOOP("hoot-core", "Need to specify a port with -whitebind: '%s'"),
QT_TRANSLATE_NOOP("hoot-core", "No Masternodes detected."),
QT_TRANSLATE_NOOP("hoot-core", "No compatible Masternode found."),
QT_TRANSLATE_NOOP("hoot-core", "No errors detected."),
QT_TRANSLATE_NOOP("hoot-core", "No matching denominations found for mixing."),
QT_TRANSLATE_NOOP("hoot-core", "No proxy server specified. Use -proxy=<ip> or -proxy=<ip:port>."),
QT_TRANSLATE_NOOP("hoot-core", "Not compatible with existing transactions."),
QT_TRANSLATE_NOOP("hoot-core", "Not enough file descriptors available."),
QT_TRANSLATE_NOOP("hoot-core", "Not enough funds to mix."),
QT_TRANSLATE_NOOP("hoot-core", "Not in the Masternode list."),
QT_TRANSLATE_NOOP("hoot-core", "Prune cannot be configured with a negative value."),
QT_TRANSLATE_NOOP("hoot-core", "Prune mode is incompatible with -coinstatsindex."),
QT_TRANSLATE_NOOP("hoot-core", "Prune mode is incompatible with -disablegovernance=false."),
QT_TRANSLATE_NOOP("hoot-core", "Prune mode is incompatible with -txindex."),
QT_TRANSLATE_NOOP("hoot-core", "Pruning blockstore..."),
QT_TRANSLATE_NOOP("hoot-core", "Reducing -maxconnections from %d to %d, because of system limitations."),
QT_TRANSLATE_NOOP("hoot-core", "Replaying blocks..."),
QT_TRANSLATE_NOOP("hoot-core", "Rescanning..."),
QT_TRANSLATE_NOOP("hoot-core", "SQLiteDatabase: Failed to execute statement to verify database: %s"),
QT_TRANSLATE_NOOP("hoot-core", "SQLiteDatabase: Failed to prepare statement to verify database: %s"),
QT_TRANSLATE_NOOP("hoot-core", "SQLiteDatabase: Failed to read database verification error: %s"),
QT_TRANSLATE_NOOP("hoot-core", "SQLiteDatabase: Unexpected application id. Expected %u, got %u"),
QT_TRANSLATE_NOOP("hoot-core", "Section [%s] is not recognized."),
QT_TRANSLATE_NOOP("hoot-core", "Session not complete!"),
QT_TRANSLATE_NOOP("hoot-core", "Session timed out."),
QT_TRANSLATE_NOOP("hoot-core", "Signing transaction failed"),
QT_TRANSLATE_NOOP("hoot-core", "Specified -walletdir \"%s\" does not exist"),
QT_TRANSLATE_NOOP("hoot-core", "Specified -walletdir \"%s\" is a relative path"),
QT_TRANSLATE_NOOP("hoot-core", "Specified -walletdir \"%s\" is not a directory"),
QT_TRANSLATE_NOOP("hoot-core", "Specified blocks directory \"%s\" does not exist."),
QT_TRANSLATE_NOOP("hoot-core", "Starting network threads..."),
QT_TRANSLATE_NOOP("hoot-core", "Submitted to masternode, waiting in queue %s"),
QT_TRANSLATE_NOOP("hoot-core", "Synchronization finished"),
QT_TRANSLATE_NOOP("hoot-core", "Synchronizing blockchain..."),
QT_TRANSLATE_NOOP("hoot-core", "Synchronizing governance objects..."),
QT_TRANSLATE_NOOP("hoot-core", "The source code is available from %s."),
QT_TRANSLATE_NOOP("hoot-core", "The specified config file %s does not exist"),
QT_TRANSLATE_NOOP("hoot-core", "The transaction amount is too small to pay the fee"),
QT_TRANSLATE_NOOP("hoot-core", "The wallet will avoid paying less than the minimum relay fee."),
QT_TRANSLATE_NOOP("hoot-core", "This is expected because you are running a pruned node."),
QT_TRANSLATE_NOOP("hoot-core", "This is experimental software."),
QT_TRANSLATE_NOOP("hoot-core", "This is the minimum transaction fee you pay on every transaction."),
QT_TRANSLATE_NOOP("hoot-core", "This is the transaction fee you will pay if you send a transaction."),
QT_TRANSLATE_NOOP("hoot-core", "Topping up keypool..."),
QT_TRANSLATE_NOOP("hoot-core", "Transaction amount too small"),
QT_TRANSLATE_NOOP("hoot-core", "Transaction amounts must not be negative"),
QT_TRANSLATE_NOOP("hoot-core", "Transaction created successfully."),
QT_TRANSLATE_NOOP("hoot-core", "Transaction fees are too high."),
QT_TRANSLATE_NOOP("hoot-core", "Transaction has too long of a mempool chain"),
QT_TRANSLATE_NOOP("hoot-core", "Transaction must have at least one recipient"),
QT_TRANSLATE_NOOP("hoot-core", "Transaction not valid."),
QT_TRANSLATE_NOOP("hoot-core", "Transaction too large"),
QT_TRANSLATE_NOOP("hoot-core", "Trying to connect..."),
QT_TRANSLATE_NOOP("hoot-core", "Unable to bind to %s on this computer (bind returned error %s)"),
QT_TRANSLATE_NOOP("hoot-core", "Unable to bind to %s on this computer. %s is probably already running."),
QT_TRANSLATE_NOOP("hoot-core", "Unable to create the PID file '%s': %s"),
QT_TRANSLATE_NOOP("hoot-core", "Unable to generate initial keys"),
QT_TRANSLATE_NOOP("hoot-core", "Unable to locate enough mixed funds for this transaction."),
QT_TRANSLATE_NOOP("hoot-core", "Unable to locate enough non-denominated funds for this transaction."),
QT_TRANSLATE_NOOP("hoot-core", "Unable to sign spork message, wrong key?"),
QT_TRANSLATE_NOOP("hoot-core", "Unable to start HTTP server. See debug log for details."),
QT_TRANSLATE_NOOP("hoot-core", "Unknown -blockfilterindex value %s."),
QT_TRANSLATE_NOOP("hoot-core", "Unknown network specified in -onlynet: '%s'"),
QT_TRANSLATE_NOOP("hoot-core", "Unknown new rules activated (versionbit %i)"),
QT_TRANSLATE_NOOP("hoot-core", "Unknown response."),
QT_TRANSLATE_NOOP("hoot-core", "Unknown state: id = %u"),
QT_TRANSLATE_NOOP("hoot-core", "Unsupported logging category %s=%s."),
QT_TRANSLATE_NOOP("hoot-core", "Upgrading UTXO database"),
QT_TRANSLATE_NOOP("hoot-core", "Upgrading txindex database"),
QT_TRANSLATE_NOOP("hoot-core", "User Agent comment (%s) contains unsafe characters."),
QT_TRANSLATE_NOOP("hoot-core", "Verifying blocks..."),
QT_TRANSLATE_NOOP("hoot-core", "Verifying wallet(s)..."),
QT_TRANSLATE_NOOP("hoot-core", "Very low number of keys left: %d"),
QT_TRANSLATE_NOOP("hoot-core", "Wallet is locked."),
QT_TRANSLATE_NOOP("hoot-core", "Wallet needed to be rewritten: restart %s to complete"),
QT_TRANSLATE_NOOP("hoot-core", "Warning: can't use %s and %s together, will prefer %s"),
QT_TRANSLATE_NOOP("hoot-core", "Warning: incorrect parameter %s, path must exist! Using default path."),
QT_TRANSLATE_NOOP("hoot-core", "Wasn't able to create wallet backup folder %s!"),
QT_TRANSLATE_NOOP("hoot-core", "Will retry..."),
QT_TRANSLATE_NOOP("hoot-core", "Wiping wallet transactions..."),
QT_TRANSLATE_NOOP("hoot-core", "You are starting with governance validation disabled."),
QT_TRANSLATE_NOOP("hoot-core", "You can not disable governance validation on a masternode."),
QT_TRANSLATE_NOOP("hoot-core", "You can not start a masternode with wallet enabled."),
QT_TRANSLATE_NOOP("hoot-core", "You need to rebuild the database using -reindex to change -addressindex"),
QT_TRANSLATE_NOOP("hoot-core", "You need to rebuild the database using -reindex to change -spentindex"),
QT_TRANSLATE_NOOP("hoot-core", "Your entries added successfully."),
QT_TRANSLATE_NOOP("hoot-core", "no mixing available."),
QT_TRANSLATE_NOOP("hoot-core", "see debug.log for details."),
};
